application:
  group: zagrodnicy (Bycza-zagroda)
  version: 0.1

#Datasource
spring:
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/trackexpensesapp?useUnicode=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #to zeby wyrzucaly sie castomowe wyjatki gdy nie ma endointu jeszcze
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  liquibase:
    change-log: db/dbchangelog-dev.yaml
    drop-first: true
  #Jpa/Hibernate:
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
    ### temporary logging for debugging
    properties:
      hibernate:
        format_sql: true

    show-sql: true

server:
  port: 8080

# OpenApi-UI
springdoc:
  api-docs:
    path: /docs/api-docs
    enabled: true
  swagger-ui:
    path: /docs/swagger
    enabled: true

    ### temprar logging for debuging
